export default {
  get_data_tendency: 'GET_DATA_TENDENTCY',
  get_data_tendency_items: 'GET_DATA_TENDENTCY_ITEMS',
  get_data_tendency_sortDest: 'GET_DATA_TENDENTCY_SORTDEST',
  get_data_tendency_popalarSort: 'GET_DATA_TENDENTCY_POPALARSORT',
  get_data_style: 'GET_DATA_STYLE',
  get_data_style_sortDesc: 'GET_DATA_STYLE_SORTDESC',
  get_data_style_popalarSort: 'GET_DATA_STYLE_POPALARSORT',
  get_data_space: 'GET_DATA_SPACE',
  get_data_space_sortDesc: 'GET_DATA_SPACE_SORTDESC',
  get_data_space_popalarSort: 'GET_DATA_SPACE_POPALARSORT',
  get_data_PengShui: 'GET_DATA_PENGSHUI',
  get_data_PengShui_sortDesc: 'GET_DATA_PENGSHUI_SORTDESC',
  get_data_PengShui_popalarSort: 'GET_DATA_PENGSHUI_POPALARSORT',
  get_data_Tips: 'GET_DATA_TIPS',
  get_data_Tips_sortDesc: 'GET_DATA_TIPS_SORTDESC',
  get_data_Tips_popalarSort: 'GET_DATA_TIPS_POPALARSORT',
  get_data_Supplies: 'GET_DATA_SUPPLIES',
  get_data_Supplies_sortDesc: 'GET_DATA_SUPPLIES_SORTDESC',
  get_data_Supplies_popalarSort: 'GET_DATA_SUPPLIES_POPALARSORT',
  get_data_StrangePoison: 'GET_DATA_STRANGEPOISON',
  get_data_StrangePoison_sortDesc: 'GET_DATA_STRANGEPOISON_SORTDESC',
  get_data_StrangePoison_popalarSort: 'GET_DATA_STRANGEPOISON_POPALARSORT',
  get_data_detail: 'GET_DATA_DETAIL',
  add_data_Email: 'ADD_DATA_EMAIL',
  search_data: 'SEARCH_DATA',
}